#!/usr/bin/env bash
# Regenerate THIRD-PARTY-NOTICES from the modules actually linked into the binary.
#
# The MIT and BSD licenses used by our dependencies require their copyright
# notices to be preserved "in all copies or substantial portions" of the
# software. A statically linked Go binary is exactly that, so anyone shipping
# ls-horizons binaries owes those upstream authors their notices.
#
# The module set is the union across all three release targets, because
# bubbletea pulls in different platform packages per GOOS and a single notices
# file ships with all of them.
#
# Usage: scripts/gen-notices.sh > THIRD-PARTY-NOTICES

set -euo pipefail

cd "$(dirname "$0")/.."

MODCACHE="$(go env GOMODCACHE)"
TARGETS=(linux darwin windows)

# Collect the union of modules linked into any target binary.
collect_modules() {
	for os in "${TARGETS[@]}"; do
		GOOS="$os" GOARCH=amd64 go list -deps ./cmd/ls-horizons 2>/dev/null |
			grep '\.' | grep -v '^github.com/litescript' |
			while read -r pkg; do
				GOOS="$os" GOARCH=amd64 go list \
					-f '{{if .Module}}{{.Module.Path}} {{.Module.Version}}{{end}}' \
					"$pkg" 2>/dev/null
			done
	done | sort -u | grep -v '^$'
}

# Go escapes uppercase letters in module cache paths as !lowercase.
escape_path() {
	printf '%s' "$1" | sed 's/\([A-Z]\)/!\l\1/g'
}

cat <<'HEADER'
THIRD-PARTY NOTICES
===================

ls-horizons is distributed as a statically linked binary that incorporates the
open source components listed below. Each is used under its own license, and
each license text is reproduced in full as those licenses require.

This file is generated by scripts/gen-notices.sh. Do not edit it by hand.

HEADER

printf 'Components (%s):\n\n' "$(collect_modules | wc -l | tr -d ' ')"
collect_modules | while read -r mod ver; do
	printf '  - %s %s\n' "$mod" "$ver"
done

collect_modules | while read -r mod ver; do
	dir="$MODCACHE/$(escape_path "$mod")@$ver"
	printf '\n\n%s\n' "$(printf '=%.0s' {1..78})"
	printf '%s %s\n' "$mod" "$ver"
	printf '%s\n\n' "$(printf '=%.0s' {1..78})"

	license_file="$(find "$dir" -maxdepth 1 \( -iname 'LICENSE*' -o -iname 'LICENCE*' -o -iname 'COPYING*' \) 2>/dev/null | head -1)"

	if [ -n "$license_file" ]; then
		cat "$license_file"
	else
		# A few modules declare their license in the README rather than
		# shipping a license file. Record that explicitly rather than
		# silently omitting the component.
		printf 'This module ships no license file. Its README declares the license as:\n\n'
		sed -n '/^## License/,/^## /p' "$dir/README.md" 2>/dev/null |
			grep -v '^## ' | grep -v '^$' || printf '  (see %s)\n' "$mod"
		printf '\nAuthor attribution per the module README:\n'
		sed -n '/^## Author/,$p' "$dir/README.md" 2>/dev/null |
			grep -v '^## ' | grep -v '^$' || true
	fi
done
